---
sudo: required
dist: xenial

env:
#  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.5.0
  - ANSIBLE_VERSION=2.3.1.0

before_install:

  # Remove unnecessary packages from Travis CI
  - sudo apt-get remove --purge --auto-remove docker-ce

  # APT packages
  - sudo apt-get update -qq
  - sudo apt-get install libgnutls28-dev git build-essential python3-dev python3-pip python-dev python-pip python-netaddr

  # PIP packages
  - sudo python3 -m pip install --upgrade pip setuptools requests pyOpenSSL netaddr ansible-lint
  - sudo python -m pip install --upgrade pip setuptools requests pyOpenSSL netaddr ansible-lint

install:
  # Install Ansible
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then
      sudo python -m pip install ansible;
    else
      sudo python -m pip install ansible==$ANSIBLE_VERSION;
    fi

script:
  # Check the playbook's syntax.
  - sudo ansible-playbook cloudbox.yml --syntax-check

  # Test the playbook.
  - sudo ansible-playbook cloudbox.yml --tags all --skip-tags "kernel,settings"
