#########################################################################
# Title:         Remote: Service Tasks                                  #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Check if '{{ outer_item }}' exists"
  stat:
    path: "/etc/systemd/system/{{ outer_item }}"
  register: service_file

- name: "Tasks for '{{ outer_item }}'"
  block:

  - name: "Stop and disable existing '{{ outer_item }}'"
    systemd:
      name: "{{ outer_item }}"
      state: stopped
      enabled: no

  - name: "Update ownership in existing '{{ outer_item }}'"
    lineinfile:
      path: "/etc/systemd/system/{{ outer_item }}"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - { regexp: '^User\s?=', line: 'User={{ user }}' }
      - { regexp: '^Group\s?=', line: 'Group={{ user }}' }

  # if applicable
  - name: "Update 'rc-addr' in existing '{{ outer_item }}'"
    replace:
      path: "/etc/systemd/system/{{ outer_item }}"
      regexp: "rc-addr=localhost:[0-9]*"
      replace: 'rc-addr=localhost:5572'

  - name: Systemd daemon-reload
    systemd: daemon_reload=yes

  when: (service_file.stat.exists)