#########################################################################
# Title:         Cloudbox: Cloudflare Role                              #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Get IP Address
  shell: "curl -s http://checkip.amazonaws.com | tail -n 1"
  register: public_ip_lookup

- name: Set 'public_ip'
  set_fact:
    public_ip: "{{ public_ip_lookup.stdout }}"

- name: Set 'record'
  set_fact:
    record: "{{ (subdomain == domain) | ternary(domain,subdomain + '.' + domain) }}"

- name: "Set DNS Record for {{ record }} to {{ public_ip }}"
  cloudflare_dns:
    account_api_token: "{{ cloudflare_api_token }}"
    account_email: "{{ email }}"
    zone: "{{ domain }}"
    state: present
    solo: true
    proxied: no
    type: A
    value: "{{ public_ip }}"
    record: "{{ subdomain }}"
  when: cloudflare_enabled
